# -*- coding: utf-8 -*-
"""EDA -Terrorism

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VzXjLCi9Pb7axVVMirtgMMppBGaIbQLR

#Mounting drive
"""

from google.colab import drive
drive.mount('/content/drive')

drive.mount("/content/drive", force_remount=True)

"""# LIBRARIES"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import  os
import seaborn as sns

"""# LOADNG DATASETS

"""

data=pd.read_csv('/content/drive/MyDrive/suicide_attacks.csv')

data.head()

data.describe

data.info()

data.shape,data.size

"""# Removing the null values"""

#Before Removing bull values

data.notnull().sum()

#After removing the null values
data=data.dropna()
data.isnull().sum()

data.set_axis(['Groups','Claim','Status','Sources','Year','Month','day','Wounded_low','Wounded_high','Killed_high','Killed_low','Civilian_low','Civilian_high','Political_low','Political_high','Security_low','Security_high','Belt_bomb','Truck_bomb','car_bomb','weapon_oth','weapon_unk','target.weapon','target.region','target.subregion','target.country','target.province','target.city','target.location','latitude','target.longitude','target.desc','target.type','target.nationality','Attackers','Female_attackers','Male_attackers','Unknown_attackers','Gender_attacker',],axis='columns')

data.head()

"""# EDA ANAYLSIS"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import plotly.express as px

plt.figure(figsize=(30,15))
sns.heatmap(data.corr(),annot=True,cmap='pink')
plt.plot()

#jointplot measuring values
sns.jointplot(data=data,x='Year',y='Sources',kind='reg')
plt.show()

sns.jointplot(x='Civilian_low',y='Sources',data=data,kind='reg',color='m')
plt.show()

#Correlation coefficientt
#heatmap
plt.figure(figsize=(24,17))
corrmat = data.corr()
sns.heatmap(corrmat, vmax=.9, square=True);
plt.show()

fig=px.bar(data.head(100), x="Attackers",y="Groups",color="Year",template="ggplot2")
fig.show()

fig=px.bar(data.head(100), x="Male_attackers",y="Groups",color="Year",template="ggplot2")
fig.show()

fig=px.bar(data.head(100), x="Female_attackers",y="Groups",color="Year",template="ggplot2")
fig.show()

#month wise Sources collection
fig = px.pie(data, values='Sources', names='Month')
fig.show()

sns.pairplot(data,corner=True)
plt.show()

"""# Final overall prediction"""

mean=data.mean
mean

#Final Prediction overall percentage data in terrorism and Suicidal attacks
mean=data.mean
mean()